swagger: "2.0"





info:

  version: "0.0.1"

  title: API Seguridad de Cifrado v1

  description: |

    API encargada de la obtención de llave privada y publica para cifrar y descifrar información.

    

host: dev-api.bancoazteca.com.mx:8080



basePath: /capitalHumano/subArea(porDefinir)/cifrado/v1



schemes:

  - https



produces:

  - application/json



securityDefinitions:

  Bearer:

    description: >

      Para acceder a la API se debe pasar un token válido en todas las consultas.

      La siguiente sintaxis se debe utilizar en el encabezado 'Authorization' :

        Bearer: 2zzLJmBAtTNIU8nF8e8XbmDvaNGs

    type: apiKey

    name: Authorization

    in: header



security:

  - Bearer: []



paths:

  /:

    get:

      description: 

        "Servicio para obtener las llaves publica y privada"

      tags:

        - Seguridad

      produces:

        - application/json


      responses:

        200:

          description: OK

          schema:

            $ref: '#/definitions/resultadoLlaves'

          examples:
            
            application/json: |- 
              {
                "mensaje": "Operación Exitosa",
                "folio": "17920191001192238557",
                "resultado": {
                  "llaves": { 
                    "llavePublica": "MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgGYl93X079nDos9r0sPhcmhn3AOKe7X2Cw5ndt2D/Nlu1FXcoZrkPW44dEGch93lqohAnzqwz35sm3voANf12SZw5LNxJ2JfoZycD6/LVLEpr8ILBbgKjDK5FghZQ4jTsdriUCKqKlV1I5+1oJOlLqcfr8sahVpNAup4kRCFgec1AgMBAAE=",
                    "llavePrivada": "MIICWgIBAAKBgGYl93X079nDos9r0sPhcmhn3AOKe7X2Cw5ndt2D/Nlu1FXcoZrkPW44dEGch93lqohAnzqwz35sm3voANf12SZw5LNxJ2JfoZycD6/LVLEpr8ILBbgKjDK5FghZQ4jTsdriUCKqKlV1I5+1oJOlLqcfr8sahVpNAup4kRCFgec1AgMBAAECgYADKTGbKNUzO+aR3JhND3Dm4i/gvCxP2SlGbNU0zZzJbbCMZ6Nok5+DBaQzU5CwwSahyL4kpswE8X9uOiOsiyMJD1ddktCfQohXxFBLZ/VyiNZlsaDra1z6BKApNXPrs+to0aGOmZ8jCYIxvrfY1EBUOVczHeYZs894DAGUBuM/kQJBAL8akS15r4DrnF/1yKLQS+dNoWLfdk3L4xrtH/DsvoXcJ06ib1dogz9shEwnLQvMDc4hQulKGwAppxNAuGc9KMsCQQCI1iL/vZg3H78EC8zesIPFjDjj6ASa3u/7zUilSwftAAW/0AGw9b7w46KeSn/VU2QXDroKs/niKQ90QbJxKy//AkBTmc209Szf2zK3kBBLmY/7Ciz10ggxFGavmtiETy0x5hOUBN9sf54bGt/taJ3+MTBA4rAg2nhhY9dhRsjk8Q5tAkABvLY1CPMlwAFsy7mOGi+SEnWmbwuf67SgPbruXkV7fMSV6s4asQP7iuhFmiyFSMm8gTNbb218sYjAsRTS2vmBAkB2oxNUp94JCeYwa1glhGcZ4d3W3vTa6G/9DfwuFNIvckm0fCEKpYKo0GyYNsUim9+0Nabw2pjzUaJktT3Eal8L"
                  }
                }
              }

             

        404:

          description: No encontrado

          schema:

            $ref: "#/definitions/error404"
          
          examples:
            
            application/json: |- 
              {
                "codigo": "404.capitalHumano-(subArea)-cifrado.1000",
                "mensaje": "Petición no válida, favor de validar su información",
                "folio": "229 20181120162829642",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#404.capitalHumano-(subArea)-cifrado.1000",
                "detalles": [
                "No se encontraron llaves de cifrado"
                ] 
              }
          

                

              

        500:

          description: Operación Inesperada

          schema:

            $ref: '#/definitions/error500'
          
          examples:
            
            application/json: |- 
              {
                "codigo": "500.Upax-Zeus-Tareas.1000",
                "mensaje": "Petición no válida, favor de validar su información",
                "folio": "22920181120162829642",
                "info": "https://baz-developer.bancoazteca.com.mx/errors#500.capitalHumano-(subArea)-cifrado.1000",
                "detalles": [
                  "Error inesperado en la operación"
                ]
              }

              



    

        

definitions:

  resultadoLlaves:

    type: object

    properties:

      mensaje:

        type: string

        description: Mensaje satisfactorio

        example: "Operación Exitosa"

      folio:

        type: string

        description: Folio de la opereación

        example: "17920191001192238557"

      resultado:

        type: object

        properties:

          llave:

            type: object

            properties:

              llavePublica:

                type: string              

                description: Llave Publica para el cliente

                example: "MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgGYl93X079nDos9r0sPhcmhn3AOKe7X2Cw5ndt2D/Nlu1FXcoZrkPW44dEGch93lqohAnzqwz35sm3voANf12SZw5LNxJ2JfoZycD6/LVLEpr8ILBbgKjDK5FghZQ4jTsdriUCKqKlV1I5+1oJOlLqcfr8sahVpNAup4kRCFgec1AgMBAAE="

              llavePrivada:

                type: string              

                description: Llave Publica para el cliente

                example: "MIICWgIBAAKBgGYl93X079nDos9r0sPhcmhn3AOKe7X2Cw5ndt2D/Nlu1FXcoZrkPW44dEGch93lqohAnzqwz35sm3voANf12SZw5LNxJ2JfoZycD6/LVLEpr8ILBbgKjDK5FghZQ4jTsdriUCKqKlV1I5+1oJOlLqcfr8sahVpNAup4kRCFgec1AgMBAAECgYADKTGbKNUzO+aR3JhND3Dm4i/gvCxP2SlGbNU0zZzJbbCMZ6Nok5+DBaQzU5CwwSahyL4kpswE8X9uOiOsiyMJD1ddktCfQohXxFBLZ/VyiNZlsaDra1z6BKApNXPrs+to0aGOmZ8jCYIxvrfY1EBUOVczHeYZs894DAGUBuM/kQJBAL8akS15r4DrnF/1yKLQS+dNoWLfdk3L4xrtH/DsvoXcJ06ib1dogz9shEwnLQvMDc4hQulKGwAppxNAuGc9KMsCQQCI1iL/vZg3H78EC8zesIPFjDjj6ASa3u/7zUilSwftAAW/0AGw9b7w46KeSn/VU2QXDroKs/niKQ90QbJxKy//AkBTmc209Szf2zK3kBBLmY/7Ciz10ggxFGavmtiETy0x5hOUBN9sf54bGt/taJ3+MTBA4rAg2nhhY9dhRsjk8Q5tAkABvLY1CPMlwAFsy7mOGi+SEnWmbwuf67SgPbruXkV7fMSV6s4asQP7iuhFmiyFSMm8gTNbb218sYjAsRTS2vmBAkB2oxNUp94JCeYwa1glhGcZ4d3W3vTa6G/9DfwuFNIvckm0fCEKpYKo0GyYNsUim9+0Nabw2pjzUaJktT3Eal8L"

  error404:

    type: object

    properties:

      codigo:

        type: string

        description: Código del error

        example: "404.capitalHumano-(subArea)-cifrado.1000"

      mensaje:

        type: string

        description: Descripción del error

        example: "Petición no válida, favor de validar su información"

      folio: 

        type: string

        description: Número de folio de la operación

        example: "22920181120162829642"

      info:

        type: string

        description: Rutas de ayuda para atender el error

        example: "https://baz-developer.bancoazteca.com.mx/errors#404.capitalHumano-(subArea)-cifrado.1000"

      detalles:

        type: array

        items:

          type: string

          example: "No se encontraron llaves de cifrado"

  error500:

    type: object

    properties:

      codigo:

        type: string

        description: Código del error

        example: "500.Upax-Zeus-Tareas.1000"

      mensaje:

        type: string

        description: Descripción del error

        example: "Petición no válida, favor de validar su información"

      folio: 

        type: string

        description: Número de folio de la operación

        example: "22920181120162829642"

      info:

        type: string

        description: Rutas de ayuda para atender el error

        example: "https://baz-developer.bancoazteca.com.mx/errors#500.capitalHumano-(subArea)-cifrado.1000"

      detalles:

        type: array

        items:

          type: string

          example: "Error inesperado en la operación"
          

  summary:

    type: object

    properties: 

      api-name:

        type: string

        description: API encargada de la obtención de llave privada y publica para cifrar y descifrar información..

        example: "API Seguridad de Cifrado v1"

      

      get:

        type: object

        properties:

          displayName: 

            type: string

            description: Servicio para obtener las llaves publica y privada.

            example: "/"

      